

on:
  push:
    branches:
      - master



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "printing files before"
        run: ls
      - uses: actions/checkout@v3
      - name: "printing files after"
        run: ls -a
    

